---
apiVersion: cert-manager.io/v1
kind: Certificate
metadata:
  name: mailu-jaackd-ca
  namespace: {{ .Values.deployment.servernamespace }}
spec:
  secretName: letsencrypt-staging
  dnsNames:
  - mailu.jaackd.com
  issuerRef:
    name: letsencrypt-staging
    kind: ClusterIssuer
    group: cert-manager.io
  isCA: true