---
apiVersion: cert-manager.io/v1
kind: Certificate
metadata:
  name: mailu-jaackd-ca
  namespace: {{ .Values.deployment.servernamespace }}
spec:
  secretName: {{ .Values.deployment.certificateSecret }}
  dnsNames:
  - "email.{{ .Values.deployment.domain }}"
  issuerRef:
    name: {{ .Values.deployment.certificateIssuer }}
    kind: ClusterIssuer
    group: cert-manager.io
  isCA: true