apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: mailu-ingress
  namespace: {{ .Values.deployment.servernamespace }}
  annotations:
    kubernetes.io/tls-acme: "true"
    certmanager.k8s.io/cluster-issuer: letsencrypt-mailu-staging
  labels:
    app: mailu
    role: mail
    tier: backend
spec:
  tls:
  - hosts:
    - "mail.{{ .Values.deployment.domain }}"
    secretName: letsencrypt-mailu-staging
  rules:
  - host: "mail.{{ .Values.deployment.domain }}"
    http:
      paths:
      - path: "/"
        pathType: ImplementationSpecific
        backend:
          service:
            name: front
            port:
              number: 80
