apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: mailu-ingress
  namespace: {{ .Values.deployment.servernamespace }}
  annotations:
    external-dns.alpha.kubernetes.io/hostname: "email.{{ .Values.deployment.domain }}"
    kubernetes.io/ingress.class: nginx
    kubernetes.io/tls-acme: "true"
    cert-manager.io/cluster-issuer: {{ .Values.deployment.certificateSecret }}
  labels:
    app: mailu
    role: mail
    tier: backend
spec:
  tls:
  - hosts:
    - "email.{{ .Values.deployment.domain }}"
    secretName: {{ .Values.deployment.certificateSecret }}
  rules:
  - host: "email.{{ .Values.deployment.domain }}"
    http:
      paths:
      - path: "/"
        pathType: ImplementationSpecific
        backend:
          service:
            name: front
            port:
              number: 80
