kind: PersistentVolumeClaim
apiVersion: v1
metadata:
  name: redis-hdd
  namespace: {{ .Values.deployment.servernamespace }}
  annotations:
    volume.beta.kubernetes.io/storage-class: "do-block-storage"
spec:
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 1Gi
---
kind: PersistentVolumeClaim
apiVersion: v1
metadata:
  name: mail-storage
  namespace: {{ .Values.deployment.servernamespace }}
  annotations:
    volume.beta.kubernetes.io/storage-class: "do-block-storage"
spec:
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 100Gi
